[theme]
primaryColor = "#F63366"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
base = "dark"
[ui]
wideMode = true
[server]
# 開発中にファイルを保存したら自動でブラウザを更新する
runOnSave = true
